import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import AppSidebar  from "@/components/app-sidebar"
import { UserProvider } from "@/components/context/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <SidebarProvider>
      <AppSidebar />
        <main className="w-full">
          <SidebarTrigger />
          <UserProvider>
            {children}
          </UserProvider>
        </main>
      </SidebarProvider>
  );
}
